### PR TITLE
PP-10035 Updated ubuntu 18.04 to ubuntu-latest

### PR DESCRIPTION
**Pull request by Rkotyank**
checked for Ubuntu 18.04 images and updated to ubuntu-latest.

### CODE REVIEW

**Review by jfharden — APPROVED** [review]
Interesting, I think this repo might not be in use anymore. Worth asking @katstevens about it since she loves archiving old repos :) 

This change is good though 👍

**Comment by Rkotyank** [comment]
> Interesting, I think this repo might not be in use anymore. Worth asking @katstevens about it since she loves archiving old repos :)
> 
> This change is good though 👍

@jfharden Will check with Kat when she is back. Thanks Jonathan

**Comment by katstevens** [comment]
Yeah, I suspect this repo has been carefully maintained (Dependabotted etc) for about 18 months when it is no longer used 😿 

We do have [public performance data available](https://www.payments.service.gov.uk/performance/) but it's not generated from this task, which [we removed last year](https://github.com/alphagov/pay-infra/pull/3223). Instead the data is generated as a JSON file from Toolbox and [updated regularly as a manual task](https://github.com/alphagov/pay-product-page/pulls?q=is%3Apr+is%3Aclosed+stats)... (this last bit was news to me!)

**Comment by Rkotyank** [comment]
> Yeah, I suspect this repo has been carefully maintained (Dependabotted etc) for about 18 months when it is no longer used 😿
> 
> We do have [public performance data available](https://www.payments.service.gov.uk/performance/) but it's not generated from this task, which [we removed last year](https://github.com/alphagov/pay-infra/pull/3223). Instead the data is generated as a JSON file from Toolbox and [updated regularly as a manual task](https://github.com/alphagov/pay-product-page/pulls?q=is%3Apr+is%3Aclosed+stats)... (this last bit was news to me!)

@katstevens should we consider archiving this repo or leave it for now

**Comment by katstevens** [comment]
I'm going to check with Krishna first.

**Pull request merged**
